### ISSUE TITLE
Trouble running examples

### ISSUE THREAD

**Issue by jason-fries** [rnfinnegan/simpleseg#1]
**_UPDATE_**: Looks like this is an issue related to the version of SimpleITK (works with 1.2.4 but not 2.X due to a AddTransform being deprecated. The current requirements.txt doesn't specify a version, so the latest version is chosen by default. 

This looks like it would be a nice framework to test out, however I'm unable to run any of your demos included in `example/`. Specifically `example/run_cardiac_segmentation.py` fails out-of-box, throwing errors related to a missing `impit` module. 
```
from impit.segmentation.atlas.label import combine_labels
```
Assuming this just needs updates to the module paths (e.g., `simpleseg/code/atlas/label.py`) module fixes some issues, but throws new errors 
```
  File "simpleseg/code/cardiac/run.py", line 178, in run_cardiac_segmentation
    reg_image, _ = initial_registration(
  File "simpleseg/code/atlas/registration.py", line 179, in initial_registration
    combined_transform.AddTransform(initial_transform)
AttributeError: 'Transform' object has no attribute 'AddTransform'
```
Are there other demo/examples I should be looking at?
